name: Prepare Release

description: 'Prepare and package a new release version.'

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  prepare-release:
    name: Prepare Release
    runs-on: macos-latest
    if: github.ref_name == 'main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Make scripts executable
        run: |
          chmod +x scripts/project_tools.sh

      - name: Bump MARKETING_VERSION and CURRENT_PROJECT_VERSION
        id: bump_version
        run: |
          bash scripts/version.sh bump ${{ github.event.inputs.bump }}

      - name: Update CHANGELOG.md
        run: |
          bash scripts/version.sh changelog

      - name: Set release version variable
        id: set_version
        run: |
          VERSION=$(bash scripts/version.sh get)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create release branch, commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${{ steps.set_version.outputs.version }}
          BRANCH_NAME="release/v$VERSION"
          git config user.name "github-actions[bot] (on behalf of ${{ github.actor }})"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b "$BRANCH_NAME"
          git add .
          git commit -m "chore(release): prepare release v$VERSION"
          git push origin "$BRANCH_NAME"

      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Instala o GitHub CLI se necessário
          if ! command -v gh &> /dev/null; then
            brew install gh
          fi
          gh auth login --with-token < <(echo "$GITHUB_TOKEN")
          gh pr create \
            --title "Release v${{ steps.set_version.outputs.version }}" \
            --body "Automated PR to release v${{ steps.set_version.outputs.version }}." \
            --head release/v${{ steps.set_version.outputs.version }} \
            --base main \
            --label release

      - name: Build XCFramework
        run: scripts/project_tools.sh build

      - name: Package XCFramework and LICENSE
        run: |
          ZIP_NAME="OSInAppBrowserLib-${{ steps.set_version.outputs.version }}.zip"
          mkdir -p release
          cp -R build/*.xcframework release/
          cp docs/LICENSE release/
          cd release
          zip -r ../$ZIP_NAME .
          cd ..
        shell: bash

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: xcframework-release
          path: OSInAppBrowserLib-*.zip
